### ISSUE TITLE
Pricing difference 

### ISSUE THREAD

**Issue by JaganANP** [ANPABHYAS/myabhyas.com#8]
For CBSE am facing a pricing difference in payment page - 7999 is displaying as 8000 [https://drive.google.com/file/d/1eRGKJ9_Fu9ox3Xr8ZZPyfL6ZQDGRf-X0/view?usp=sharing](url)

**Comment by selva070** [comment]
@JaganANP change the percentage value to **42.8601** and check on the plan discount.
